### ISSUE TITLE
bootstrap.less wasn't found

### ISSUE THREAD

**Issue by jehrhardt** [gdub22/ember-cli-less#17] opened 2015-03-30 08:23 UTC
I have the following problem with using Bootstrap:

```
FileError: 'bootstrap.less' wasn't found. Tried - /Users/jehrhardt/code/github/bug-demo/tmp/tree_merger-tmp_dest_dir-dENfKObT.tmp/app/styles/bootstrap.less,/Users/jehrhardt/code/github/bug-demo/tmp/tree_merger-tmp_dest_dir-dENfKObT.tmp/app/styles/bootstrap.less,/Users/jehrhardt/code/github/bug-demo/tmp/tree_merger-tmp_dest_dir-dENfKObT.tmp/bootstrap.less,bootstrap.less in /Users/jehrhardt/code/github/bug-demo/tmp/tree_merger-tmp_dest_dir-dENfKObT.tmp//app/styles/app.less on line 1, column 1:
1 @import 'bootstrap';
```

I did the following steps:

1. Create a new Ember application
2. Install less support [as documented](http://www.ember-cli.com/#less)
3. Install bootstrap [like in the examples](https://github.com/gdub22/ember-cli-less#examples)
4. Start the application: `npm start`

This results in the above error. I have put a [demonstration of the problem on Github](https://github.com/jehrhardt/ember-cli-bootstrap-less-bug).

My system:

* ember-cli: `0.2.1`
* node: `0.12.1`
* npm: `2.7.3`

**Comment by antonfefilov** [comment] 2015-03-30 09:45
+1

**Comment by antonfefilov** [comment] 2015-03-30 10:23
I guess this is because of the #16. You have 2 ways to solve this problem immediately:
1) you can use previous version of the ember-cli-less (1.2.0 in this case) or 2) you can move lessOptions from `Brocfile.js` to the `config/environment.js`. 

``` javascript
  if (environment === 'development') {
    ...
    ENV.lessOptions = { paths: [ 'bower_components/bootstrap/less' ] }
    ...
  }

**Comment by jehrhardt** [comment] 2015-03-30 10:45
Hmmh, how will this be in the future? Will future versions require `lessOptions` in `Brocfile.js` or in `config/environment.js`?

**Comment by antonfefilov** [comment] 2015-03-30 12:38
Based on the discussion mentioned above I guess future versions will require `lessOptions` in `Brocfile.js`. @gdub22 can you confirm this?

**Comment by gdub22** [comment] 2015-03-30 13:39
Options should continue to be defined in the Brocfile as described in the readme.  If that isn't working, downgrade to a previous version for the time being.  I'll test everything and get the addon back in full working order today.

**Comment by stefanpenner** [comment] 2015-04-02 22:01
this is a change/regression in ember-cli related to setupPreprocessRegistry. Investigating it now.

**Comment by gdub22** [comment] 2015-04-02 22:11
Reference: https://github.com/ember-cli/ember-cli/issues/3701

**Comment by gdub22** [comment] 2015-04-07 19:29
@jehrhardt this is fixed in 1.3.1.  Continue to define options in Brocfile, as described in the readme.  Sorry for the confusion/regression.

**Closed by gdub22** 2015-04-07 19:29 UTC

**Comment by beerlington** [comment] 2015-07-17 16:11
Any chance this issue has crept back up again? I just upgraded an app from ember-cli 0.2.7 to 1.13.1 and am suddenly getting this error. I've tried to make sure I'm on the latest version of everything else, so I'm not sure if this is related or what.

**Comment by gdub22** [comment] 2015-07-17 17:29
@beerlington I assume you already accounted for the Brocfile.js -> ember-cli-build.js change in ember-cli 1.13.1?

**Comment by beerlington** [comment] 2015-07-17 17:44
@gdub22 I didn't make that change because the ember-cli release notes say it's a deprecation, and I figured it would work but give me a deprecation warning. I'll make that change and see if it helps. Thanks!

**Comment by gdub22** [comment] 2015-07-17 17:47
@beerlington I believe they only recently added the deprecation / backwards compatibility (on ember-cli master) because of such confusion.  So in ember-cli 1.13.1, I think the whole Brocfile is probably ignored.
