### ISSUE TITLE
Issue generating source maps

### ISSUE THREAD

**Issue by wattyrevBT** [gdub22/ember-cli-less#51] opened 2016-05-09 16:25 UTC
If I leave sourceMaps enabled in lessOptions, I end up with an error like this:

> Invalid mapping: {"generated":{"line":4391,"column":2},"source":"../bittitan-css/lib/bootstrap/3.3.5/type.less","original":{"line":1,"column":null},"name":null}

When I narrow down the issue, it seems that it breaks when I have a media query nested inside a selector. Example:
```
.my-selector {
    @media (max-width: @screen-sm) {
        // styles
    }
}
```

So, I could either refactor any instances of nested media queries or set sourceMap to equal false.

**Comment by knownasilya** [comment] 2016-05-09 18:26
Duplicate of #50

**Closed by knownasilya** 2016-05-09 18:26 UTC
