### ISSUE TITLE
Build fail without app.less 

### ISSUE THREAD

**Issue by dukex** [gdub22/ember-cli-less#30] opened 2015-10-12 20:15 UTC
Using the config:

```
  var app = new EmberApp(defaults, {
    // Add options here
    outputPaths: {
      app: {
        css: {
          'theme': '/assets/theme.css'
        }
      }
    }
  });
``` 

The build fails with this message:

```
Build failed.
File not found: /app/styles/app.less
in any of the following include paths:
  /tmp/ember-cli-less-app/tmp/broccoli_merge_trees-output_path-QqDjTSPH.tmp
Error: File not found: /app/styles/app.less
in any of the following include paths:
  /tmp/ember-cli-less-app/tmp/broccoli_merge_trees-output_path-QqDjTSPH.tmp
```

**Comment by gdub22** [comment] 2015-10-12 20:39
If you want to use less, you need to create app.less.  Please see the readme

**Comment by gdub22** [comment] 2015-10-12 20:42
Whoops, reopened. Are you saying you just want to output theme.css, and not have app.css?

**Comment by dukex** [comment] 2015-10-12 22:01
Yes, I dont have app.css, like README config:

``` js
var app = new EmberApp({
  outputPaths: {
    app: {
      css: {
        'theme-orange': '/assets/theme-orange.css',
        'theme-purple': '/assets/theme-purple.css'
      }
    }
  }
});
```

The theme-* files `import` my general styles

**Comment by knownasilya** [comment] 2015-10-13 14:45
Trying the same thing, but with an app defined, also seeing the same issue.

**Comment by knownasilya** [comment] 2015-10-13 15:55
I don't think that config means you don't have an app.css, it just means you aren't overriding it. Since mine still generates even if I have it setup like the above.

**Comment by gdub22** [comment] 2015-10-13 16:05
confirmed with the dummy app. I have a PR in the works

**Comment by gdub22** [comment] 2015-10-13 16:39
Scratch that PR.  I believe this should be fixed in ember-cli.
https://github.com/ember-cli/ember-cli/issues/4948

The solution for now is just to create an empty app.less file

**Comment by knownasilya** [comment] 2015-11-06 17:51
Closing this in favor of the ember-cli issue. Please contribute there.

**Closed by knownasilya** 2015-11-06 17:51 UTC
